{
"method":"POST",
"url":"/zone/add",
"data":
{
"name":"tcpwave.com",
"template_name":"TCPWave-template",
"description":"",
"dnssec_enable":"no",
"nsec_option":"NSEC3",
"restrictedZone":"no",
"monitoringService":"yes",
"dmzVisible":"no",
"activeDirectoryEnable":"no",
"dcObjectIds":[],
"dcAclObjects":[],
"secureActiveDirectoryEnable":"no",
"serial_format":"DATE",
"zoneRR":[],
"organization_name":"EARTH"
}
}
